add new system checks
arrilot/bitrix-systemcheck pull request #1
Opened 2019-02-18 06:51 UTC by fruiting

2019-02-19 07:32 UTC, arrilot requested changes

2019-02-19 07:32 UTC, arrilot commented on src/Checks/Bitrix/EncodingIsCorrect.php
> +            $this->logError('Неверное значение ' . $name . ' в .settings.php');
Здесь не хватает  $this->result = false;

2019-02-19 07:32 UTC, arrilot commented on src/Checks/Bitrix/EncodingIsCorrect.php
> +            $this->logError('Неверное значение ' . $name . ' в dbconn.php');
$this->result = false;

2019-02-19 07:32 UTC, arrilot commented on src/Checks/Bitrix/EncodingIsCorrect.php
> +                'value' => 2,
Надо сделать проверку более общей, чтобы она подходила и для сайтов в utf-8 и для cp-1251. Кодировку передавать в проверку через конструктор, по-умолчанию utf-8

2019-02-19 07:32 UTC, arrilot commented on src/Checks/Custom/Mail.php
> +namespace Arrilot\BitrixSystemCheck\Checks\Custom;
В Битриксе есть уже проверки на это
Отправка почты
Отправка почтового сообщения больше 64Кб

Значит их надо делать в Arrilot\BitrixSystemCheck\Checks\Custom и на основе кода из ядра битрикса

2019-02-19 07:32 UTC, arrilot commented on src/Checks/Bitrix/DataBaseCheck.php
> +        $this->connection = mysqli_connect(
Что будет в старых проектах где расширение mysqli не установлено вообще? Надо постараться вообще обойтись без прямого коннекта к базе через mysqli

2019-02-19 07:32 UTC, arrilot commented on src/Checks/Bitrix/DataBaseCheck.php
> +        $mysqlTimestamp = strtotime($this->connection->query('SELECT NOW()')->fetch_assoc()['NOW()']);
Здесь скорее всего будут ложные срабатывания и надо хотя бы abs($serverTimestamp - $mysqlTimestamp) > 1 поставить

2019-02-19 07:32 UTC, arrilot commented on src/Checks/Bitrix/SitesCheck.php
> +                    $this->logError('Отсутствует символьная ссылка в корне проекта ' . $site['SERVER_NAME']);
Проверки некорректные, для стандартной установки битрикса там не симлинк, а прямо сама папка. У тебя же в таких случаях будут лететь ошибки

2019-02-19 07:32 UTC, arrilot commented on src/Checks/Custom/DiskSpaceCheck.php
> +        if (disk_free_space('/') < 500000000) {
500000000 нужно сделать настраиваемым через конструктор проверки 
__constructor($limit = 500)

2019-02-19 07:32 UTC, arrilot commented on src/Checks/Custom/RamCheck.php
> +        if ($memory < 500000) {
Аналогично

2019-02-19 07:32 UTC, arrilot commented on src/Checks/Custom/RamCheck.php
> +        $systemFile = fopen('/proc/meminfo', 'r');
Если этот файл не удалось открыть (например мы на windows), то проверку надо пометить как пропущенную

2019-02-19 07:32 UTC, arrilot commented on src/Checks/Custom/Mail.php
> +        $notSentMail = db()->query('SELECT ID FROM b_event WHERE SUCCESS_EXEC != "Y"');
1. Нельзя использовать хэлперы скелетона, проверки должны работать и без него.
2. Проверка вообще реализована некорректно. В системе могут быть письма с SUCCESS_EXEC != 'Y' и отсюда будут постоянно лететь алерты.
Рекомендую пока отложить эту проверку совсем

2019-02-25 19:13 UTC, arrilot commented on src/Checks/Custom/DiskSpaceCheck.php
> +        $this->limitBytes = $limit * 1000000;
А ты уверен что тут не должно быть 1024*1024?

2019-02-25 19:17 UTC, arrilot commented on src/Checks/Custom/RamCheck.php
> +        $this->limitKiloBytes = $limit * 1000;
Аналогично

2019-02-25 19:17 UTC, arrilot commented on src/Checks/Bitrix/UpdateServerCheck.php
> +        return (new CSiteCheckerTest)->check_update();
Здесь нет никакого вывода ошибок через logError()

2019-02-25 19:52 UTC, fruiting commented on src/Checks/Custom/DiskSpaceCheck.php
> +        $this->limitBytes = $limit * 1000000;
Да, ты прав. Запутался, когда гуглом переводил http://joxi.ru/Y2LlOG4U9R9dP2 :)

2019-03-07 08:24 UTC, merged